src/web/Controllers/ProductosController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Entidades.Articulos;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.Extensions.Logging;
using servicios;
using web.Models;

namespace web.Controllers
{
  public class ProductosController : Controller
  {
    private readonly IServiciosStock _stock;

    public ProductosController(ILogger<ProductosController> logger, IServiciosStock stock)
    {
      logger.LogWarning("Creado controlador {nombre}", nameof(ProductosController));
      _stock = stock;
    }

    [AllowAnonymous]
    public IActionResult Inicio()
    {
      return View();
    }

    /// <summary>
    /// Consulta el stock de libros segun criterio de titulo y/o editorial
    /// </summary>
    /// <returns></returns>
    public IActionResult LibrosPorCriterio()
    {
      //  var modelo = new CriterioViewModel();

      return View();
    }

    [HttpPost]
    public IActionResult LibrosPorCriterio(CriterioViewModel criterio, SegundoViewModel modelo)
    {
      //  en este momento, el binder no solamente enlazo las propiedades sino que validó el modelo con los datos
      //  disponibles ==> data annotations!!!
      //
      if (ModelState.IsValid)
      {
        //  quiero que el modelo TAMBIEN sea invalido si AMBAS propiedades estan vacias...
        //
        if (string.IsNullOrWhiteSpace(criterio.Editorial) && string.IsNullOrWhiteSpace(criterio.Titulo))
        {
          ModelState.AddModelError<CriterioViewModel>(model => model,
            "[ERROR MODELO] No podemos buscar sin ningun criterio...");

          return View();
        }

        var resultado = _stock.GetLibrosFromCriterio($"{criterio.Titulo} {criterio.Editorial}");

        return View("ListaLibros", resultado);
      }
      else
      {
        ModelState.Clear();

        if (TryValidateModel(criterio))
        {
          if (TryValidateModel(modelo))
          {
            var resultado = _stock.GetLibrosFromCriterio($"{criterio.Titulo} {criterio.Editorial}");

            return View("ListaLibros", resultado);
          }

          //  quiere decir que el error esta en el segundo...
          //  iteramos en la coleccion de errores...
          foreach (var campo in ModelState.Keys)
          {
            //  ojo cada campo puede tener mas de un error diferente...
            var errores = ModelState[campo].Errors;

            foreach (var error in errores)
              ModelState.AddModelError<SegundoViewModel>(model => model,
                $"Campo {campo} ==> {error.ErrorMessage} - Valor actual: {ModelState[campo].AttemptedValue}");
          }
          return View();
        }
        return View();
      }
    }

    /// <summary>
    /// Retorna una lista de los libros mostrando ID y titulo
    /// </summary>
    /// <returns></returns>
    public IActionResult Listar()
    {
      var modelo = _stock.ObtenerTitulosDeEditorial(null);

      ViewData.Model = modelo;

      ViewBag.Encabezado = "Lista de TODOS los ID y Titulos";

      return View();
    }

    [HttpGet]
    public IActionResult BuscarAPI()
    {
      return View();
    }

    [HttpGet]
    [Authorize(Roles = "Administrador, StockAdmin")]
    public IActionResult NuevoAutor()
    {
      return View();
    }

    [HttpPost]
    [Authorize(Roles = "Administrador, StockAdmin")]
    public IActionResult NuevoAutor(Autor nuevo)
    {
      //  aca no tenemos atributos ni problemas de binding por lo tanto siempre el modelo sera correcto!
      //
      if (ModelState.IsValid)
      {
        if (string.IsNullOrWhiteSpace(nuevo.Nombre))
          ModelState.AddModelError<Autor>(autor => autor.Nombre, "El nombre no puede estar en blanco!!!");
        else
        {
          if (nuevo.Nombre == "Sarasa")
            ModelState.AddModelError<Autor>(autor => autor.Nombre, "Ese nombre de autor no puede existir...");
          else
          {
            //  modelo correcto para agregarlo a la base de datos
            //
            if (_stock.AgregarAutor(nuevo))
            {
              ViewBag.NuevoAutor = nuevo;

              ModelState.Clear();

              return View();
            }
            else
            {
              ModelState.AddModelError<Autor>(autor => autor, "Error ingresando datos en la base de datos... revisar LOG");

              return View(nuevo);
            }
          }
        }

        return View(nuevo);
      }
      return View();
    }

  }
}

src/web/Views/Productos/BuscarAPI.cshtml
@{
  ViewData["Title"] = "Busqueda Interactiva";
}

@section scripts_links
{
  <script src="~/lib/handlebars.js/handlebars.js"></script>
  <script src="~/lib/vue/vue.js"></script>
  <script src="~/lib/axios/axios.js"></script>
}

@section style_page
{
  <style>
    [v-cloak] {
      display: none;
    }
  </style>
}


@section script_page
{
  
  <script id="cardLibroTemplate" type="text/template">

    <div>
      <div class="d-flex flex-column" style="background-color: antiquewhite;">
        <h3>{{item.titulo}}</h3>
        <img :src="item.linkImagen" width="200" />
        <p>{{item.costo}}</p>
      </div>
    </div>
 
  
  </script>

  <script>
    var libros;

    $(document).ready(function () {
      /*
        ------------------------------

                COMPONENTES VUE

        ------------------------------
      */

      //  representa una tarjeta con datos de un libro en particular
      //  podremos usarlo mediante el tag <cardLibro>
      //
      Vue.component("cardlibro",
        {
          //  id del template que debe estar en un <script> con formato moustache
          //
          template: "#cardLibroTemplate",

          //  lista de propiedades que puedo setear desde el tag, pueden representar valores simples o un objeto
          //  en nuestro caso sera un Libro (o LibroDTO)
          //
          props: ["item"]
        });


      libros = new Vue({
        el: "#appVue",

        data: {
          lista: [],
          criterio: "",
          filtroInput: ""
        },

        //  permite crear variables que se pueden bindear pero que dependen de otras...
        //
        computed: {
          mostrar: function () {
            return this.criterio !== "";
          }
        },

        methods: {
          getLibros: function () {
            /**
              {
                "titulo": "Pro OpenSolaris",
                "costo": 2951.32,
                "linkImagen": "http://...gbs_api"
              },
            */
            axios({
                method: "get",
                url: `/api/libros/${this.criterio}`
              })
              .then(function(response) {
                libros.lista = response.data;
                //  console.log(response);
              })
              .catch(function(error) {
                //  en axios el objeto jqXHR esta en error.request
                const jqXHR = error.request;

                switch (jqXHR.status) {
                default:
                  {
                    //  manejo normal de errores...
                    const titulo = `${jqXHR.status} - ${jqXHR.statusText}`;

                    console.log(titulo);
                  }
                  break;
                }
                console.log(error);
              });
          }
        },

        //  observa una variable para ver cuando cambia...
        //
        watch: {
          filtroInput: function (newFiltro, oldFiltro) {
            if (newFiltro.length >= 3) {
              this.criterio = newFiltro;
              this.getLibros();
            } else
              this.criterio = "";
          }
        }
      });

      $("#filtroBusqueda").focus();

    });

  </script>

}

<div id="appVue">

  <div class="row">

    <div class="offset-1 col-9">
      <div class="card m-4">
        <h4 class="card-header text-white bg-primary text-center">Buscar Libros Interactivamente</h4>

        <div class="card-body">

          <div class="form-group">
            <label for="filtroBusqueda">Criterio de Busqueda...</label>
            <input type="text" name="filtroBusqueda" id="filtroBusqueda"
                   v-model="filtroInput"
                   placeholder="Ingresar criterio de busqueda..."
                   class="form-control form-control-sm" autofocus="autofocus" />
          </div>

        </div>
      </div>
    </div>
  </div>

  <div class="row">

    <div class="offset-1 col-10" v-show="mostrar">
      <h1>Lista de Libros segun el criterio [ {{ criterio }} ]</h1>

      <div class="row">

        <div v-cloak v-for="libro in lista" class="col-3 p-5">
          <cardlibro v-bind:item="libro"></cardlibro>
        </div>
      </div>
    </div>

  </div>

</div>

src/web/Views/Productos/Inicio.cshtml
@{
    ViewData["Title"] = "Inicio";
}

src/web/Views/Productos/LibrosPorCriterio.cshtml
@model CriterioViewModel
@{
  ViewData["Title"] = "Buscar Libros por Criterio";
}

<div class="row">

  <div class="offset-1 col-9">
    <div class="card m-4">
      <h4 class="card-header text-white bg-primary text-center">Buscar Libros</h4>

      <div asp-validation-summary="ModelOnly" class="text-danger"
           data-summary-titulo="Lista de errores que impiden ingresar el usuario"></div>

      <form asp-controller="Productos" asp-action="LibrosPorCriterio" method="post">

        <div class="card-body">

          <div class="form-group">
            <label asp-for="Titulo">Titulo</label>
            <input asp-for="Titulo" class="form-control form-control-sm" autofocus="autofocus" />

            <span asp-validation-for="Titulo" class="text-danger"></span>
          </div>

          <div class="form-group">
            <label asp-for="Editorial">Editorial</label>
            <input asp-for="Editorial" class="form-control form-control-sm" />

            <span asp-validation-for="Editorial" class="text-danger"></span>
          </div>

          <div class="form-group">
            <label for="nombre">Nombre</label>
            <input class="form-control form-control-sm" name="nombre" id="nombre" />
          </div>

          <div class="form-group">
            <label for="id">ID</label>
            <input class="form-control form-control-sm" name="id" id="id" />
          </div>

          <div class="form-group">
            <label for="fecha">Fecha</label>
            <input class="form-control form-control-sm" name="fecha" id="fecha" />
          </div>

        </div>

        <div class="card-footer">
          <button class="btn btn-primary float-right" type="submit">Buscar</button>
        </div>

      </form>

    </div>
  </div>

</div>

src/web/Views/Productos/ListaLibros.cshtml
@using Entidades.Articulos
@using Microsoft.Extensions.Configuration
@model IEnumerable<Libro>
@inject IConfiguration Configuracion

@{
  ViewData["Title"] = "ListaLibros";
}

<h1>Lista de Libros Segun Criterio...</h1>

<h2>@Configuracion["mensaje"]</h2>

<div class="container">

  @foreach (var item in Model)
  {
    <partial name="_DetalleLibro" model="item" />
  }

</div>

src/web/Views/Productos/Listar.cshtml
@model List<(Guid id, string titulo)>

@{
  ViewData["Title"] = "Listar";
}

@section script_page
{
  <script>
    $(document).ready(function() {
      window.alert("Listar!!!");
    });
  </script>
}

<h1>@ViewBag.Encabezado</h1>
  
@foreach (var item in Model)
{
  <div>
    <p>@item.id</p>
    <p>@item.titulo</p>
  </div>
}

src/web/Views/Productos/NuevoAutor.cshtml
@using Entidades.Articulos
@model Autor
@{
  ViewData["Title"] = "NuevoAutor";

  Autor nuevo = ViewBag.NuevoAutor as Autor;
}

@if (nuevo != null)
{
  <h3>Se agrego un nuevo autor @nuevo.Nombre con ID = @nuevo.ID</h3>
}

<div class="row">

  <div class="offset-1 col-9">
    <div class="card m-4">
      <h4 class="card-header text-white bg-primary text-center">Agregar Nuevo Autor</h4>

      <div asp-validation-summary="ModelOnly" class="text-danger"
           data-summary-titulo="Lista de errores que impiden ingresar el autor"></div>

      <form asp-controller="Productos" asp-action="NuevoAutor" method="post">

        <div class="card-body">

          <div class="form-group">
            <label asp-for="Nombre">Nombre del Autor</label>
            <input asp-for="Nombre" class="form-control form-control-sm" autofocus="autofocus" />

            <span asp-validation-for="Nombre" class="text-danger"></span>
          </div>

          <div class="form-group">
            <label asp-for="Biografia">Biografia</label>
            <textarea asp-for="Biografia" class="form-control form-control-sm"></textarea>

            <span asp-validation-for="Biografia" class="text-danger"></span>
          </div>

        </div>

        <div class="card-footer">
          <button class="btn btn-primary float-right" type="submit">Agregar</button>
        </div>

      </form>

    </div>
  </div>

</div>